### ISSUE TITLE
Chiusura

### ISSUE THREAD

**Issue by AlfioEmanueleFresta** [CroceRossaItaliana/gaia-android#76]
@ciopper90 dall'aggiornamento a Jorvik questa app non funziona più.

Sarebbe necessario fare un aggiornamento all'applicazione, e mostrare un messaggio che spieghi che, da gennaio, è possibile visitare https://gaia.cri.it per utilizzare le funzionalità di Gaia.

Per favore puoi farlo ASAP perché aprono tonnellate di ticket

**Comment by ciopper90** [comment]
Ciao, 
Domanda rapida. Avete cambiato le api per il login??

Copelli

**Comment by ciopper90** [comment]
Ciao,
Che frase inserisco?

Copelli

**Comment by AlfioEmanueleFresta** [comment]
@ciopper90 

```
La nuova versione di Gaia ha portato tante novità e puoi ora accedere 
a tutte le funzionalità complete, dal tuo smartphone e/o tablet, 
senza bisogno di installare alcuna app. 

Ti basta aprire il tuo browser e andare su https://gaia.cri.it [ndr: link].

Questa app non funzionerà più, puoi disinstallarla.
```

Grazie mille

**Comment by ciopper90** [comment]
https://www.dropbox.com/s/qq50b1z4p9zeqxg/gaia-android-1.0.4.apk?dl=1

Ecco il link al file. Se confermate pubblico subito sullo store android.

Copelli

**Comment by AlfioEmanueleFresta** [comment]
Ottimo grazie @ciopper90

**Comment by ciopper90** [comment]
Prego. Caricato sullo store. 
@AlfioEmanueleFresta Puoi chiudere.
